ALTER VIEW [dm].[VINTAGES]
AS
WITH CTE AS
	(
		SELECT	1	AS RN
		UNION ALL
		SELECT	RN+1	AS	RN
		FROM	CTE
		WHERE	RN < 100
	)
SELECT	V1.CREDITID																	AS	CREDITID,				--	PK
		V1.AMT_MOB0																	AS	AMT_MOB0,
		V1.AMT_MOB1																	AS	AMT_MOB1,
		V1.AMT_MOB2																	AS	AMT_MOB2,
		V1.AMT_MOB3																	AS	AMT_MOB3,
		V1.AMT_MOB4																	AS	AMT_MOB4,
		V1.AMT_MOB5																	AS	AMT_MOB5,
		V1.AMT_MOB6																	AS	AMT_MOB6,
		V1.AMT_MOB7																	AS	AMT_MOB7,
		V1.AMT_MOB8																	AS	AMT_MOB8,
		V1.AMT_MOB9																	AS	AMT_MOB9,
		V1.AMT_MOB10																AS	AMT_MOB10,

		V1.AMT_PD_MOB0																AS	AMT_PD_MOB0,
		V1.AMT_PD_MOB1																AS	AMT_PD_MOB1,
		V1.AMT_PD_MOB2																AS	AMT_PD_MOB2,
		V1.AMT_PD_MOB3																AS	AMT_PD_MOB3,
		V1.AMT_PD_MOB4																AS	AMT_PD_MOB4,
		V1.AMT_PD_MOB5																AS	AMT_PD_MOB5,
		V1.AMT_PD_MOB6																AS	AMT_PD_MOB6,
		V1.AMT_PD_MOB7																AS	AMT_PD_MOB7,
		V1.AMT_PD_MOB8																AS	AMT_PD_MOB8,
		V1.AMT_PD_MOB9																AS	AMT_PD_MOB9,
		V1.AMT_PD_MOB10																AS	AMT_PD_MOB10
FROM	(
			SELECT	ROW_NUMBER() OVER(ORDER BY T1.RN)														AS	CREDITID,
					CAST(ABS(CHECKSUM(NEWID()) % 10000 + 1) * (ABS(CHECKSUM(NEWID()) % 20 + 1)) AS MONEY)	AS	AMT_MOB0,
					CAST(ABS(CHECKSUM(NEWID()) % 10000 + 1) * (ABS(CHECKSUM(NEWID()) % 20 + 1)) AS MONEY)	AS	AMT_MOB1,
					CAST(ABS(CHECKSUM(NEWID()) % 10000 + 1) * (ABS(CHECKSUM(NEWID()) % 20 + 1)) AS MONEY)	AS	AMT_MOB2,
					CAST(ABS(CHECKSUM(NEWID()) % 10000 + 1) * (ABS(CHECKSUM(NEWID()) % 20 + 1)) AS MONEY)	AS	AMT_MOB3,
					CAST(ABS(CHECKSUM(NEWID()) % 10000 + 1) * (ABS(CHECKSUM(NEWID()) % 20 + 1)) AS MONEY)	AS	AMT_MOB4,
					CAST(ABS(CHECKSUM(NEWID()) % 10000 + 1) * (ABS(CHECKSUM(NEWID()) % 20 + 1)) AS MONEY)	AS	AMT_MOB5,
					CAST(ABS(CHECKSUM(NEWID()) % 10000 + 1) * (ABS(CHECKSUM(NEWID()) % 20 + 1)) AS MONEY)	AS	AMT_MOB6,
					CAST(ABS(CHECKSUM(NEWID()) % 10000 + 1) * (ABS(CHECKSUM(NEWID()) % 20 + 1)) AS MONEY)	AS	AMT_MOB7,
					CAST(ABS(CHECKSUM(NEWID()) % 10000 + 1) * (ABS(CHECKSUM(NEWID()) % 20 + 1)) AS MONEY)	AS	AMT_MOB8,
					CAST(ABS(CHECKSUM(NEWID()) % 10000 + 1) * (ABS(CHECKSUM(NEWID()) % 20 + 1)) AS MONEY)	AS	AMT_MOB9,
					CAST(ABS(CHECKSUM(NEWID()) % 10000 + 1) * (ABS(CHECKSUM(NEWID()) % 20 + 1)) AS MONEY)	AS	AMT_MOB10,

					CAST(ABS(CHECKSUM(NEWID()) % 10000 + 1) * (ABS(CHECKSUM(NEWID()) % 20 + 1)) AS MONEY)	AS	AMT_PD_MOB0,
					CAST(ABS(CHECKSUM(NEWID()) % 10000 + 1) * (ABS(CHECKSUM(NEWID()) % 20 + 1)) AS MONEY)	AS	AMT_PD_MOB1,
					CAST(ABS(CHECKSUM(NEWID()) % 10000 + 1) * (ABS(CHECKSUM(NEWID()) % 20 + 1)) AS MONEY)	AS	AMT_PD_MOB2,
					CAST(ABS(CHECKSUM(NEWID()) % 10000 + 1) * (ABS(CHECKSUM(NEWID()) % 20 + 1)) AS MONEY)	AS	AMT_PD_MOB3,
					CAST(ABS(CHECKSUM(NEWID()) % 10000 + 1) * (ABS(CHECKSUM(NEWID()) % 20 + 1)) AS MONEY)	AS	AMT_PD_MOB4,
					CAST(ABS(CHECKSUM(NEWID()) % 10000 + 1) * (ABS(CHECKSUM(NEWID()) % 20 + 1)) AS MONEY)	AS	AMT_PD_MOB5,
					CAST(ABS(CHECKSUM(NEWID()) % 10000 + 1) * (ABS(CHECKSUM(NEWID()) % 20 + 1)) AS MONEY)	AS	AMT_PD_MOB6,
					CAST(ABS(CHECKSUM(NEWID()) % 10000 + 1) * (ABS(CHECKSUM(NEWID()) % 20 + 1)) AS MONEY)	AS	AMT_PD_MOB7,
					CAST(ABS(CHECKSUM(NEWID()) % 10000 + 1) * (ABS(CHECKSUM(NEWID()) % 20 + 1)) AS MONEY)	AS	AMT_PD_MOB8,
					CAST(ABS(CHECKSUM(NEWID()) % 10000 + 1) * (ABS(CHECKSUM(NEWID()) % 20 + 1)) AS MONEY)	AS	AMT_PD_MOB9,
					CAST(ABS(CHECKSUM(NEWID()) % 10000 + 1) * (ABS(CHECKSUM(NEWID()) % 20 + 1)) AS MONEY)	AS	AMT_PD_MOB10
			FROM	CTE T1
			CROSS JOIN CTE T2
		) V1;
