CREATE VIEW [dm].[XPD]
AS
WITH CTE AS
	(
		SELECT	1	AS RN
		UNION ALL
		SELECT	RN+1	AS	RN
		FROM	CTE
		WHERE	RN < 100
	)
SELECT	V1.CREDITID																	AS	CREDITID,				--	PK
		V1.PD_TYPE																	AS	PD_TYPE
FROM	(
			SELECT	ROW_NUMBER() OVER(ORDER BY T1.RN)						AS	CREDITID,
					'FPD'													AS	PD_TYPE
			FROM	CTE T1
			CROSS JOIN CTE T2
		) V1;